# Introduction to Python


## A Quick tour of Python
========================

In this notebook, we will cover a wide variety of topics about the Python language to give you a broad overview of the data structures it offers, some use cases for them and the kinds of tasks they can be used for. 

** Arrays
** Sets
** Dictionaries
** 2D Arrays


In [1]:
my_list = ['p','r','o','g','r','a','m','i','z']
# elements 3rd to 5th
print(my_list[2:5])

# elements beginning to 4th
print(my_list[:-5])

# elements 6th to end
print(my_list[5:])

# elements beginning to end
print(my_list[:])
#my_list

['o', 'g', 'r']
['p', 'r', 'o', 'g']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


__Range__

The `range()` built-in function creates a list of integers, and is used a lot in Python because the `for` loop operates over lists.

The simplest way to use the range function is to just specify the number of elements or, in another way of thinking about it, specify the stop value:

In [2]:
print(range(15))

range(0, 15)


In [3]:
range(3,10,2)

range(3, 10, 2)

# **Excercise:**
how we can create a list of integers [2, 4, 6, 8] using range  ?

output: 
2
4
6
8
other list: 
3
4
5

In [5]:
for i in range(3,4,5):
    list=[print(i)]
    list

3


In [4]:
for i in range(2,10,2):
    list=[print(i)]
    list

2
4
6
8


# Set
=====
Sets are used to store multiple items in a single variable.
Set is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Tuple, and Dictionary, all with different qualities and usage.

A set is a collection which is unordered, unchangeable*, and unindexed.
****Unordered means that the items in a set do not have a defined order.****
    **Set items can appear in a different order every time you use them, and cannot be referred to by index or key.**
***Set items are unchangeable, meaning that we cannot change the items after the set has been created.**
    **Once a set is created, you cannot change its items, but you can remove items and add new items.**
    
**Duplicates Not Allowed**

Sets cannot have two items with the same value.
* Note: Set items are unchangeable, but you can remove items and add new items.

Python also provides the `set` data structure, which can be created using curly brackets.

# How to create sets of integer number and string

In [6]:
a = {1, 2, 3, 4}
a

{1, 2, 3, 4}

In [7]:
 string_set= {"apple", "banana", "cherry"}
string_set

{'apple', 'banana', 'cherry'}

# Duplicate values will be ignored, create a set by duplicating some values

In [8]:
string_set= {"apple", "banana", "cherry", 'apple'}
string_set

{'apple', 'banana', 'cherry'}

In [9]:
a = {1, 2, 3, 4, 1}
a

{1, 2, 3, 4}

# How Get the Length of a Set?

To determine how many items a set has, use the len() function.

In [10]:
a = {1, 2, 3, 4, 1}
len(a)

4

# What is Set Items - Data Types? how to find the types of set ? Create 3 different sets of string, numbers and true false.

Set items can be of any data type: 

In [11]:
set1 = {"apple", "banana", "cherry"}
set2 = {1, 5, 7, 9, 3}
set3 = {True, False, False} 
#type(set1)
#type(set2)
type(set3)

set

# Can a set can contain different data types: e.g. set= {1, 'a', "kk", 3.4}
# set of mixed datatypes

In [12]:
set1 = {"abc", 34, True, 40, "male", 3.4} 
set1

{3.4, 34, 40, True, 'abc', 'male'}

# What will be the output???????

In [13]:
list={1,2,3,4,5,2,9,2,3,4}
list
len(list)
#type(list)

6

# duplicate item are removed, e.g. list={1,2,3,4,5,2,9,2,3,4} output= {1,2,3,4,5,9}

#### type(a)

In [14]:
b = {2, 3, 4, 5}
b.add(3)
b

{2, 3, 4, 5}

# How to add item in a set via add()

In [15]:
a.add(10)
a

{1, 2, 3, 4, 10}

# Sets can be used to carry out mathematical set operations like union, intersection, difference and symmetric difference.
We can do this with operators or methods.

# Intersection, Union , symmetric difference of two sets using opeartor, please perform on integer, character and string set

In [16]:
a & b  # Intersection

{2, 3, 4}

In [17]:
a | b # Union

{1, 2, 3, 4, 5, 10}

In [18]:
a ^ b # symmetric difference

{1, 5, 10}

In [19]:
a - b

{1, 10}

# All the above opeation using function 

In [20]:
# Set union method
# initialize A and B
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}



# How to use union Method

In [21]:
# use union function
 #A.union(B)
A.union(B)
# use union function on B
#B.union(A)


{1, 2, 3, 4, 5, 6, 7, 8}

# How to use intersection method

In [22]:
A.intersection(B)
# use intersection function on B
#B.intersection(A)


{4, 5}

# How to use difference function 

In [23]:
# use difference function on A
A.difference(B)


# use - operator on B
#B - A


# use difference function on B
#B.difference(A)


{1, 2, 3}

# How to use symatric_difference function 

In [24]:
# use symmetric_difference function on A
A.symmetric_difference(B)

# use symmetric_difference function on B
#B.symmetric_difference(A)


{1, 2, 3, 6, 7, 8}

# Exercise: set={1,2,'3','ad',"ok",(3,4,5)}, how many item will be there in the set, and will be length of the set


In [25]:
set={1,2,'3','ad',"ok",(3,4,5)}
set

{(3, 4, 5), 1, 2, '3', 'ad', 'ok'}

In [26]:
len(set)

6

# Excercise: a={}, can we create this type of set ?How many item will be there in this set 

In [27]:
a={}
type(a)

dict

# if you write set={}, remember that a dictionary will be created not a set , please practice it

# How to remove set item by discard(), practice it by using different sets

In [28]:
a= {1,2,3,4,5}
a.discard(4)
a


{1, 2, 3, 5}

# what will be the answer: a={1,2,3,4,5}     b={4,5,6,7,8}
#a|b
#a.union(b)
#b.union(a)
#a&b
#a.intersection(b)
#a^b

In [29]:
a={1,2,3,4,5}
b={4,5,6,7,8}
a|b
#a.union(b)
#b.union(a)
#a&b
#a.intersection(b)
#a^b

{1, 2, 3, 4, 5, 6, 7, 8}

# The set() Constructor

It is also possible to use the set() constructor to make a set.

# Home work, using the set () constructor , convert the following into set
numbers_list = [1, 2, 3, 4, 5, 5, 3, 2]

numbers_tuple = (1, 2, 3, 4, 5, 5, 4, 3)

numbers_dict = {1:'one',2:'two',3:'three'}

mystr = 'Hello World'


# Excercise: How to delete all item from the set?

In [30]:
set1= {1,2,3,4}
#set1.clear()
set1

{1, 2, 3, 4}

# poping item from set

In [31]:
set1.pop()
set1

{2, 3, 4}

# Set Membership Test: how to test wheathe a member exist in the set or not

We can test if an item exists in a set or not, using the in keyword.

In [32]:
set1={2,4,5,6,7,8}
print(4 in set1)

True


# we can remove and return an item using the pop() method.

Since set is an unordered data type, there is no way of determining which item will be popped. It is completely arbitrary.

We can also remove all the items from a set using the clear() method.

# Homework: Please perform the following operation on set
Important set operation

Method
					Description
			
add()
					Adds an element to the set
			
clear()
					Removes all elements from the set
			
copy()
					Returns a copy of the set
			
difference()
					Returns the difference of two or more sets as a new set
			
difference_update()
					Removes all elements of another set from this set
			
discard()
					Removes an element from the set if it is a member. (Do nothing if the element is not in set)
			
intersection()
					Returns the intersection of two sets as a new set
			
intersection_update()
					Updates the set with the intersection of itself and another
			
isdisjoint()
					Returns True if two sets have a null intersection
			
issubset()
					Returns True if another set contains this set
			
issuperset()
					Returns True if this set contains another set
			
pop()
					Removes and returns an arbitrary set element. Raises KeyError if the set is empty
			
remove()
					Removes an element from the set. If the element is not a member, raises a KeyError
			
symmetric_difference()
					Returns the symmetric difference of two sets as a new set
			
symmetric_difference_update()
					Updates a set with the symmetric difference of itself and another
			
union()
					Returns the union of sets in a new set
			
update()
					Updates the set with the union of itself and others


## Dictionaries
============

If you're familiar with the computer science "hash" or "map" data structures, a dictionary is essentially the Python equivalent of those.

For those unfamiliar with Python dictionaries, we can use an actual dictionary as a mental model.  In a dictionary you have words, and those words have definitions that are associated with them. You might have multiple definitions, but they are all associated with one word's entry in the dictionary.

This maps to the data structure very well: each entry is a key-value pair, where the keys are the words, and the values are the definitions.  If there are multiple definitions, you might instead have a list of definitions instead of a single definition for the value, but the idea is the same.

So in Python we can create an empty dictionary with a pair of braces (curly brackets):

# How to create simple dictionary, print the type of dictionary, length of dictionary

In [33]:
pets = {'dogs':5, 'cats':4}
pets

{'dogs': 5, 'cats': 4}

In [34]:
type(pets)

dict

In [35]:
len(pets)

2

In [36]:
pets['dogs']

5

# How to add element to the dictionary

In [37]:
animal={'loin':4,'dog':3,'flaw':2,'jaw':5}
#len(animal)
#type(animal)
#animal['flaw']
#animal['dog'] +=3
#animal['jaw']=33
animal['sa']=22
animal

{'loin': 4, 'dog': 3, 'flaw': 2, 'jaw': 5, 'sa': 22}

In [38]:
pets = {'dogs':5, 'cats':4}
pets

{'dogs': 5, 'cats': 4}

In [39]:
pets['dogs'] += 2
pets

{'dogs': 7, 'cats': 4}

In [40]:
pets['fox'] = 3
pets

{'dogs': 7, 'cats': 4, 'fox': 3}

In [41]:
pets['dogs']= 4
pets

{'dogs': 4, 'cats': 4, 'fox': 3}

# What if we try to add a key value pair whose key is already present?

# You can ask for the list of keys, of key-value pairs, or just the values.

# How to print keys of the list or dictionary and values of the key

In [42]:
pets.keys()

dict_keys(['dogs', 'cats', 'fox'])

In [43]:
pets.items()

dict_items([('dogs', 4), ('cats', 4), ('fox', 3)])

In [44]:
pets.values()

dict_values([4, 4, 3])

In [45]:
a={'10':1,'20':2,'30':3,'40':4,'50':5}
a['60']=6
#a.keys()
#a.items()
#a.values()
#'20' in a
#2 not in a

In [47]:
a

{'10': 1, '20': 2, '30': 3, '40': 4, '50': 5, '60': 6}

In [46]:
pets

{'dogs': 4, 'cats': 4, 'fox': 3}

# To find weather a key is present in dictionary or not

In [48]:
'cats' in pets

True

In [49]:
'cats' not in pets

False

In [50]:
students={}

In [51]:
type(students)

dict

### Accessing items with `get()`

You can instead access values with the `get()` method which has a little more capability.  Get returns the value associated with a key, like indexing, but if the key doesn't exist it doesn't raise an error, but instead returns a default value `None`.

In [53]:
student['3']

NameError: name 'student' is not defined

In [52]:
print (student.get('3'))

NameError: name 'student' is not defined

In [54]:
students={}
students['1']="Zaviyar"
students["2"]='amir'
students['3']="khattak"
students["4"]='Rovaid'
students

{'1': 'Zaviyar', '2': 'amir', '3': 'khattak', '4': 'Rovaid'}

In [55]:
#students['5']
print(students.get('2','yes'))
#print(students.get('7','yes'))

amir


# how we can show list of dictionary function??? please explore some of them

# We can have a dictionary inside a dictionary

In [56]:
college = {'name': "COMSATS", "students":student}
college

NameError: name 'student' is not defined

In [57]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [58]:
x=thisdict['model']
print(x)
print(thisdict.get('year'))
thisdict["year"]= 2000
thisdict

Mustang
1964


{'brand': 'Ford', 'model': 'Mustang', 'year': 2000}

In [59]:
newdic= dict(brand1= 'ford' ,model='janpan',year='20000')
newdic

{'brand1': 'ford', 'model': 'janpan', 'year': '20000'}

In [60]:
car =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
car.values()
car.get("model")
print(car["model"])

Mustang


In [61]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
#print(thisdict)
#for x in thisdict:
 #   print(thisdict[x])
    
#for x in thisdict.values():
 #   print(x)
for x,y in thisdict.items():
    print(x,y)
thisdict.pop("model")
thisdict
thisdict['model1']="yoho"
thisdict
thisdict.popitem()
thisdict

brand Ford
model Mustang
year 1964


{'brand': 'Ford', 'year': 1964}

## Mathematical Operations
-----------------------
By now, we're pretty use to lists being the workhorse sequential data structure in Python. It's great for many things, but it turns out that another data structure, the NumPy array, provides a different set of functionality that is really useful -- especially for numeric computations.

Here we start with a list, and illustrate the difference in syntax for mathematical operations on a list and an array.

Imagine you want to add 1 to every element in a sequence. Here is a comparison between doing this with an array and a list.

Let's look at a list

In [62]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

If you add 1 to a list, you get an error because you can't add list and int types.

In [63]:
#a+5
a.insert(2,8)
a

[1, 2, 8, 3, 4]

# How to add 1 to each element of the list

In [64]:
a = [1, 2, 3, 4]
[x +1 for x in a]

[2, 3, 4, 5]

This will work, but it is a bit cryptic to the uninitiated:

#### List Comprehension

In [65]:
[val + 1 for val in a]

[2, 3, 4, 5]

### Numpy - arrays
But if we convert `a` to a NumPy `array`, then it does work:

# How to convert a list into numpy array? please perform converting integer list, string list, mixed list into respective Numpy-array

In [66]:
import numpy as np 
a = np.array(a)

In [67]:
a

array([1, 2, 3, 4])

# Excercise: How to change the array element? e.g. if array= ([1, 2, 3, 4]) 
output: ([6, 7, 8, 9])

In [68]:
a+5

array([6, 7, 8, 9])

This is the first thing that the array provides: when you perform a mathematical operation on an array, the operation is performed on every element of the array.  So the result is 1+5 is 6, 2+5 is 7, 3+5 is 8 and 4+5 is 9.

Operations on two Arrays
------------------------

NumPy always carries out element-by-element operations when operating on two arrays.  Here are several examples with `+`,`*`, and `**` operators.

Let's create another array `b`:

# How to create array

In [69]:
b = np.array([2, 3, 4, 5])
b

array([2, 3, 4, 5])

# Creating two array a, b and then performing 
a+b
a*b
a**a
Operations on arrays
Note: Take array with different length

In [70]:
import numpy as np
a=np.array([2,3,4,5])
b=[3,4,5,6]
b=np.array(b)

In [71]:
a
b

array([3, 4, 5, 6])

# Excercise: What will be the ouput?

In [72]:
a+b
#a*b
#a**a

array([ 5,  7,  9, 11])

They both have 4 elements.  If we add a and b:

In [73]:
a + b

array([ 5,  7,  9, 11])

then the operation is performed element-by-element: 1+2 is 3, 2+3 is 5, 3+4 is 7 and 4+5 is 9.

This doesn't just work for addition.  You can multiply:

In [74]:
a*b

array([ 6, 12, 20, 30])

You can exponentiate:

In [75]:
a**b

array([    8,    81,  1024, 15625], dtype=int32)

In [76]:
import numpy as np
a=np.array([2,3,4,5])
a

array([2, 3, 4, 5])

# How to find sum, standard deviation, mean of array element

In [ ]:
#np.sum(a)
#np.std(a)
#np.mean(a)
#np.argmax(a)


All operations are performed element-by-element.

In [77]:
np.sum(a)

14

In [78]:
np.std(a)

1.118033988749895

In [79]:
np.mean(a)

3.5

# How to create 2-d array randomly within a fixed range and predifined rows and colums

In [80]:
import numpy as np
np.random.seed(0)
x1= np.random.randint(10,size=(3,4))
x1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [81]:
import numpy as np
myarray=np.array([[1,2,3],[4,5,6]])
print(myarray)

[[1 2 3]
 [4 5 6]]


In [82]:
import numpy as np
np.zeros((3,4))
#np.ones((3,4))
#np.random.random((2,2))
#np.empty((2,3))
#np.full((2,3),3)
#np.arange(10,25,5)
#np.linspace(0,2,9)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [84]:
np.random.random((2,2))

array([[0.05671298, 0.27265629],
       [0.47766512, 0.81216873]])

In [85]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [86]:
np.full((2,3),3)

array([[3, 3, 3],
       [3, 3, 3]])

# start, stop, step (excluding end point)

In [87]:
np.arange(10,25,5)

array([10, 15, 20])

# start , stop number of intervel to be genrated

In [88]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

# Reshaping the original array

In [89]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
#a.shape
#a.dtype.name
#a.ndim # dimension
a.itemsize # length or one array element in bytes

4

# How to sum array element, find the maximum and minimum element in the array

In [91]:
import numpy as np
a= np.arange(6)
a
a.sum()
a.min()
a.max()

5

In [92]:
import numpy as np
b= np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
import numpy as np
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [97]:
import numpy as np
a= np.array([1,2,3,4])
list=[3,4,5,6]
b=np.array(list)
a
b

array([3, 4, 5, 6])

In [98]:
a+b

array([ 4,  6,  8, 10])

In [99]:
(a+b).sum()

28

In [100]:
a=np.arange(10)
a
b=np.arange(10)**3
b

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [101]:
b[2:5]
b[:8]
b[-1]
b[:-2]
b[0:-5]

array([ 0,  1,  8, 27, 64], dtype=int32)

In [102]:
b[:6]=100
b

array([100, 100, 100, 100, 100, 100, 216, 343, 512, 729], dtype=int32)

In [103]:
b[::-1]

array([729, 512, 343, 216, 100, 100, 100, 100, 100, 100], dtype=int32)

In [104]:
def f (x,y):
    return 10*x+y

b=np.fromfunction(f,(5,4))
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

#### Numpy arrays - more examples later

[Back To The Table of Contents](#TOC)